version: "3.8"

services:
  server:
    image: twentycrm/twenty:${SOFTWARE_VERSION_TAG}
    restart: always
    ports:
      - "172.17.0.1:39973:3000"
    environment:
      PORT: 3000
      PG_DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      SERVER_URL: ${SERVER_URL}
      FRONT_BASE_URL: ${SERVER_URL}

      ENABLE_DB_MIGRATIONS: "true"

      SIGN_IN_PREFILLED: "false"
      STORAGE_TYPE: local
      STORAGE_LOCAL_PATH: .local-storage
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      LOGIN_TOKEN_SECRET: ${LOGIN_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      FILE_TOKEN_SECRET: ${FILE_TOKEN_SECRET}

      EMAIL_FROM_ADDRESS: ${EMAIL_FROM_ADDRESS}
      EMAIL_SYSTEM_ADDRESS: ${EMAIL_FROM_ADDRESS}
      EMAIL_FROM_NAME: "Twenty"
      EMAIL_DRIVER: smtp
      EMAIL_SMTP_HOST: ${EMAIL_SMTP_HOST}
      EMAIL_SMTP_PORT: ${EMAIL_SMTP_PORT}
      PASSWORD_RESET_TOKEN_EXPIRES_IN: 5m
      FRONT_AUTH_CALLBACK_URL: ${SERVER_URL}/verify
      IS_SIGN_UP_DISABLED: "${IS_SIGN_UP_DISABLED}"
    depends_on:
      - db
    volumes:
      - ./server-local-data:/app/.local-storage

  db:
    image: twentycrm/twenty-postgres:${SOFTWARE_VERSION_TAG}
    restart: always
    volumes:
      - ./db-data:/bitnami/postgresql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 172.17.0.1:51175:5432

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:26565:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
